services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    ports:
      - "8080:80"
    volumes:
      - ./nextcloud_data:/var/www/html
    environment:
      - POSTGRES_DB=localhost
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
